name: radio_auto_m3u
description: A Flutter Android Auto compatible radio app with M3U/PLS/OPML support
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Audio & background playback
  just_audio: 0.9.36
  audio_service: 0.18.12
  just_audio_background: 0.0.1-beta.15

  # Storage & networking
  shared_preferences: 2.2.2
  http: 1.1.2
  xml: 6.3.0

  # Utilities
  collection: 1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/stations/
