name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/upload-artifact@v4

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.1' # Set your Flutter SDK version

    - name: Enable flutter cache
      run: flutter pub get

    - name: Run Flutter doctor
      run: flutter doctor

    - name: Get dependencies
      run: flutter pub get

    - name: Clean previous builds
      run: flutter clean

    - name: Build APK (release)
      run: flutter build apk --release

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: radio_auto_m3u-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
